version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: crypto
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://crypto:crypto@postgres:5432/crypto
      - REDIS_URL=redis://redis:6379/0
    ports: ["8000:8000"]

  frontend:
    build: ./crypto-trader-frontend
    volumes:
      - ./crypto-trader-frontend:/app
    ports: ["5173:5173"]

volumes:
  pgdata:
