# Generated by Django 4.2.7 on 2025-10-21 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=30)),
                ('price_per_unit', models.DecimalField(decimal_places=8, max_digits=30)),
                ('total', models.DecimalField(decimal_places=8, max_digits=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.cryptoasset')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=16, default=0, max_digits=30)),
                ('avg_price', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.cryptoasset')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='trades.wallet')),
            ],
        ),
    ]
